# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: feaa54771346d1a36ed184d0cb92970d3b93cb1f2179a175555ff114716e7f937bc8bb9664b1444ff207dcb5aec911ca1e767323bf0ffbb1e5ed8c2151348e78

test:
  secret_key_base: 5da6dde2ff520e6e155ed9e482c483028cfa728251248cc47fe64717caec15fa7b33264bbde2dc6a5c15b0a9a95455df4a377eaf48e33041a265a00627c2b350

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
